188 subscription plans
JaviFdez7/ISPP-G1-Talent pull request #317
Opened 2024-04-06 18:57 UTC by carzarrei

@motero2k , a pesar de no tener conflictos, por favor comprueba que todo funciona correctamente, porque a mi me dan errores que están arreglados tiempo atras y que a @andresdominguezruiz no le dan actualmente al probarlo en la misma rama.

2024-04-07 15:30 UTC, motero2k requested changes
Se deben resolver los conflictos y añadir los cambios comentados por Andrés en la reunión.

2024-04-07 19:37 UTC, carzarrei commented
Se ha arreglado el fallo del JWT al crear usuarios, el resto de la funcionalidad no se ha tocado

2024-04-07 20:50 UTC, carzarrei commented
Se ha comproado las principales funcionalidades y se han arreglado varios errores

2024-04-09 17:58 UTC, motero2k approved these changes

2024-04-09 20:09 UTC, motero2k commented
Esta bien pero hay que controlar las actualizaciones de la foto de perfil. Eso a otra issue. Puedes mergear

2024-04-09 20:22 UTC, merged